### ISSUE TITLE
运行./star.js 时出现的问题

### ISSUE THREAD

**Issue by wangkr** [hustcer/star#24]
/home/wangkr/star/star.js:11
let _       = require('lodash'),
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by hustcer** [comment]
你用的node版本是多少？执行的什么命令？

**Comment by hustcer** [comment]
极有可能是因为你用的`node.js`版本过低导致的

**Comment by wangkr** [comment]
v0.12.7版的啊

**Comment by hustcer** [comment]
用这个命令试试：`node --harmony ./star.js` 
默认情况下node 没有启用对`--harmony`的支持，需要手工启用下，等node 1.0发布后可能会启用

**Comment by wangkr** [comment]
解决了。

**Comment by hustcer** [comment]
嗯，好的
