### ISSUE TITLE
无法创建有效地软件连接

### ISSUE THREAD

**Issue by Jexceed** [hustcer/star#44]
从源代码安装Star(sudo npm install --production)，使用软连接访问Star时，出现以下问题：

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'symbols.yaml'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object._.filter._.filter._.filter._.filter.syms [as getFilteredSymbols](/Users/ChiangEarl/Documents/Project/git/star/lib/trace.js:31:36)
    at Object.actions.TRACE (/Users/ChiangEarl/Documents/Project/git/star/star.js:128:29)
    at doCmd (/Users/ChiangEarl/Documents/Project/git/star/star.js:161:20)
    at Object.<anonymous> (/Users/ChiangEarl/Documents/Project/git/star/star.js:165:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

<img width="682" alt="star" src="https://cloud.githubusercontent.com/assets/4215430/11740109/4d0da994-a02b-11e5-8a17-11302ede8f1c.png">

**Comment by hustcer** [comment]
1. 你可以试试从源码目录运行`star`命令;
2. 或者头一次通过 `star -f /absolute/path/to/symbols.yaml`初始化下，下一次直接执行 star

**Comment by Jexceed** [comment]
谢谢，设置yaml文件目录后问题解决
