### ISSUE TITLE
运行star出现问题

### ISSUE THREAD

**Issue by volfmath** [hustcer/star#46]
yntaxError: /Users/oujun/.star.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:430:27)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.getSymbolFilePath (/usr/local/lib/node_modules/.star_npminstall/star/0.3.5/star/lib/common.js:45:26)
    at Object.getFilteredSymbols (/usr/local/lib/node_modules/.star_npminstall/star/0.3.5/star/lib/trace.js:31:56)
    at Object.trace (/usr/local/lib/node_modules/.star_npminstall/star/0.3.5/star/star.js:128:29)
    at doCmd (/usr/local/lib/node_modules/.star_npminstall/star/0.3.5/star/star.js:161:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/.star_npminstall/star/0.3.5/star/star.js:165:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

**Comment by hustcer** [comment]
你可以把`/Users/oujun/.star.json`这个文件删掉试试

**Comment by volfmath** [comment]
删了 出现这个

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'symbols.yaml'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.getFilteredSymbols (/usr/local/lib/node_modules/.star_npminstall/star/0.3.5/star/lib/trace.js:31:36)
    at Object.trace (/usr/local/lib/node_modules/.star_npminstall/star/0.3.5/star/star.js:128:29)
    at doCmd (/usr/local/lib/node_modules/.star_npminstall/star/0.3.5/star/star.js:161:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/.star_npminstall/star/0.3.5/star/star.js:165:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

**Comment by volfmath** [comment]
源码安装方式搞定了 谢谢

**Comment by hustcer** [comment]
第一次运行的时候需要加-f或--file参数指定股票数据文件(推荐采用绝对路径)，之后可以省略该参数;
