### ISSUE TITLE
star err

### ISSUE THREAD

**Issue by tt3tb** [hustcer/star#6]
module.js:489
    throw err;
          ^
SyntaxError: /Users/local/.star.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:486:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.Common.getSymbolFilePath (/usr/local/lib/node_modules/star/lib/common.js:43:26)
    at Object._.filter._.filter._.filter.syms [as getFilteredSymbols](/usr/local/lib/node_modules/star/lib/trace.js:31:53)
    at Object.actions.TRACE (/usr/local/lib/node_modules/star/star.js:109:29)
    at doCmd (/usr/local/lib/node_modules/star/star.js:137:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/star/star.js:141:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by hustcer** [comment]
你用的什么系统？执行的什么命令？执行其他命令有问题么? 你可以试着把`/Users/local/.star.json`这个文件删掉，重新通过 `-f`参数指定配置文件试试，路径要用绝对路径。

**Comment by tt3tb** [comment]
是路径的问题，问题已解决，谢谢。

**Comment by hustcer** [comment]
不客气
